app:
  env: APP_ENV
  debug: APP_DEBUG
  port: APP_PORT
postgres:
  host: POSTGRES_HOST
  port: POSTGRES_PORT
  username: POSTGRES_USERNAME
  password: POSTGRES_PASSWORD
  database: POSTGRES_DATABASE
  sslmode: POSTGRES_SSLMODE